# Generated by Django 3.1.2 on 2020-10-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('foto', models.FileField(default=None, upload_to='actividades/')),
            ],
        ),
    ]
