# Generated by Django 3.1.2 on 2020-10-26 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='foto',
            new_name='imagen',
        ),
    ]
