# Generated by Django 3.1.2 on 2020-12-01 02:49

import actividades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20201026_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='instrucciones',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.FileField(default=None, upload_to=actividades.models.content_file_name),
        ),
    ]
